GET http://localhost:3000/users

###
GET http://localhost:3000/subscribers/624e3be7c27db31408f5e472


###

POST http://localhost:3000/users
Content-Type: application/json

{
    "email": "emilianorios99@gmail.com",
    "password": "123",
    "firstName": "Emiliano",
    "lastName": "Rios",
    "phoneNumber": "3476599932",
    "address": "Montevideo 1255, Rosario, Santa Fe",
    "employeeFlag": true
}


###
DELETE http://localhost:3000/subscribers/624e3dd8c27db31408f5e481

###
PATCH http://localhost:3000/subscribers/624e3be7c27db31408f5e472
Content-Type: application/json

{
  "subscribedToChannel": "CallMeCarson"
}